### PR TITLE
Ignore invalid params instead of returning an error

### LINKED ISSUE #90: Ignore parameters which don't have a = following their name
Per https://mimesniff.spec.whatwg.org/#parse-a-mime-type it ignores the invalid parameters instead of failing to parse the mime type.

mime 0.2 did the right thing but mime 0.3 returns `Err(FromStrError { inner: MissingEqual })`

### PR DESCRIPTION
**Pull request by Eijebong**
Fixes #90

### CODE REVIEW

**Comment by Eijebong** [comment]
Mhh this is wrong for "text/css;blah", will try to fix

**Comment by georgeroman** [comment]
@Eijebong Besides rebasing, is this work finished?

**Comment by Eijebong** [comment]
I think it was yeah

**Comment by georgeroman** [comment]
Sorry, I somehow missed your response. There were some tests in https://github.com/servo/servo/pull/23229 that failed due to this issue (https://github.com/servo/servo/pull/23229#issuecomment-484605716). Would it be possible to rebase so that this can get merged?

**Comment by ferjm** [comment]
ping @Eijebong ^

**Comment by Eijebong** [comment]
@ferjm Forgot about that. Will try to have a look tonight

**Pull request closed without merging**
